name: shorto
description: Calculator for making a home-made Porto.

version: 1.1.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  golden_toolkit: ^0.8.0
  provider: ^4.1.3
  sentry_flutter: ^4.0.4
  auto_size_text: ^2.1.0
  math_expressions: ^2.0.2
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.1
  font_awesome_flutter: ^8.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.14.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
